-- Phase 3: expenses with optional receipt object metadata.

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    safe_house_id BIGINT NOT NULL REFERENCES safe_houses (id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
    currency TEXT NOT NULL DEFAULT 'CAD',
    note TEXT NOT NULL DEFAULT '',
    spent_on DATE NOT NULL,
    receipt_key TEXT,
    receipt_content_type TEXT,
    receipt_bytes INT,
    created_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT expenses_receipt_meta_chk CHECK (
        (receipt_key IS NULL AND receipt_content_type IS NULL AND receipt_bytes IS NULL)
        OR (receipt_key IS NOT NULL AND receipt_content_type IS NOT NULL AND receipt_bytes IS NOT NULL AND receipt_bytes > 0)
    )
);

CREATE INDEX expenses_safe_house_id_idx ON expenses (safe_house_id);
CREATE INDEX expenses_spent_on_idx ON expenses (spent_on);
