-- Operational problems and significant changes per safe house (feedback §6, Document 50).
-- Separate from residents and from safeguarding concerns. Rows are never deleted.

CREATE TABLE operational_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    safe_house_id BIGINT NOT NULL REFERENCES safe_houses (id) ON DELETE RESTRICT,
    identified_on DATE NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    effect TEXT NOT NULL DEFAULT '',
    action_taken TEXT NOT NULL DEFAULT '',
    rhl_request TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open',
    closed_on DATE,
    closure_notes TEXT NOT NULL DEFAULT '',
    created_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT operational_issues_category_chk CHECK (category IN (
        'building_maintenance', 'utilities', 'safety_security', 'food_supplies',
        'staffing_agent', 'capacity_occupancy', 'service_availability', 'other_change'
    )),
    CONSTRAINT operational_issues_description_chk CHECK (char_length(trim(description)) > 0),
    CONSTRAINT operational_issues_status_chk CHECK (status IN ('open', 'resolved', 'closed')),
    CONSTRAINT operational_issues_closure_chk CHECK (
        (status = 'open' AND closed_on IS NULL AND closure_notes = '')
        OR (status <> 'open' AND closed_on IS NOT NULL AND closed_on >= identified_on
            AND char_length(trim(closure_notes)) > 0)
    )
);

CREATE INDEX operational_issues_house_status_idx ON operational_issues (safe_house_id, status);
CREATE INDEX operational_issues_range_idx ON operational_issues (identified_on, closed_on);
