-- Month confirmations (feedback §7): an Agent or RHL user confirms that data
-- entry for a safe house and reporting month is complete. Every confirmation
-- is kept; the latest per house and month is the current one. The fingerprint
-- is a SHA-256 over the month's underlying data at confirmation time.

CREATE TABLE month_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    safe_house_id BIGINT NOT NULL REFERENCES safe_houses (id) ON DELETE RESTRICT,
    month DATE NOT NULL,
    fingerprint TEXT NOT NULL,
    confirmed_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT month_confirmations_month_chk CHECK (EXTRACT(DAY FROM month) = 1),
    CONSTRAINT month_confirmations_fingerprint_chk CHECK (fingerprint ~ '^[0-9a-f]{64}$')
);

CREATE INDEX month_confirmations_house_month_idx
    ON month_confirmations (safe_house_id, month, confirmed_at DESC, id DESC);
