#!/usr/bin/env bash
# Start a Cloudflare quick tunnel to the local Beacon app for phone testing.
# WebAuthn requires BASE_URL / RP ID / origins to match the tunnel hostname.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ADDR_PORT="${ADDR_PORT:-8080}"
TUNNEL_ENV="${TUNNEL_ENV:-.local/tunnel.env}"
LOG="${TMPDIR:-/tmp}/beacon-cloudflared.log"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. Run: make setup" >&2
  exit 1
fi

mkdir -p .local
rm -f "$LOG" "$TUNNEL_ENV"

echo "Starting cloudflared quick tunnel → http://127.0.0.1:${ADDR_PORT}"
echo "(Keep this terminal open. Ctrl-C stops the tunnel.)"
echo

cloudflared tunnel --url "http://127.0.0.1:${ADDR_PORT}" >"$LOG" 2>&1 &
CF_PID=$!
cleanup() {
  kill "$CF_PID" >/dev/null 2>&1 || true
  wait "$CF_PID" 2>/dev/null || true
}
trap cleanup EXIT

url=""
for _ in $(seq 1 60); do
  if ! kill -0 "$CF_PID" 2>/dev/null; then
    echo "cloudflared exited early:" >&2
    cat "$LOG" >&2
    exit 1
  fi
  url="$(grep -Eo 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$LOG" | head -1 || true)"
  if [[ -n "$url" ]]; then
    break
  fi
  sleep 0.5
done

if [[ -z "$url" ]]; then
  echo "Timed out waiting for tunnel URL. Log:" >&2
  cat "$LOG" >&2
  exit 1
fi

host="${url#https://}"
cat >"$TUNNEL_ENV" <<EOF
# Generated by scripts/tunnel.sh — do not commit.
BASE_URL=${url}
WEBAUTHN_RP_ID=${host}
WEBAUTHN_RP_ORIGINS=${url}
SECURE_COOKIES=true
EOF

echo "Tunnel URL:  $url"
echo "Wrote:       $TUNNEL_ENV"
echo
echo "In another terminal, restart the app with tunnel WebAuthn settings:"
echo "  make run-tunnel"
echo
echo "Then open $url on your phone (same Cloudflare network path)."
echo "Passkeys enrolled on localhost will NOT work on the tunnel host — re-invite / enroll again."
echo
tail -f "$LOG"
